### ISSUE TITLE
VARLiNGAM statsmodels

### ISSUE THREAD

**Issue by TomVanDeuren** [cdt15/lingam#86]
Dear, if I run VARLiNGAM with the latest version of statsmodels (0.14.0) installed, I seem to be getting an error:
```
Traceback (most recent call last):
  File ".../var_lingam.py", line 79, in <module>
    model.fit(df1)
  File ".../opt/anaconda3/envs/lingam/lib/python3.9/site-packages/lingam/var_lingam.py", line 95, in fit
    M_taus, lags, residuals = self._estimate_var_coefs(X)
  File ".../opt/anaconda3/envs/lingam/lib/python3.9/site-packages/lingam/var_lingam.py", line 279, in _estimate_var_coefs
    fitted = var.fit(maxlags=lag, ic=None, trend="nc")
  File ".../opt/anaconda3/envs/lingam/lib/python3.9/site-packages/statsmodels/tsa/vector_ar/var_model.py", line 656, in fit
    raise ValueError("trend '{}' not supported for VAR".format(trend))
ValueError: trend 'nc' not supported for VAR
```
With an older version (0.12.2) everything seems to be working fine.

Thanks

**Comment by nick111** [comment]
I believe the error is due to a recent modification of statsmodels. According to this article (https://github.com/statsmodels/statsmodels/pull/7593 ), all "nc" has been replaced with "n". All codes in lingam that pass "nc" to statsmodels functions should be changed to "n".

**Comment by haraoka-screen** [comment]
@TomVanDeuren
Thank you for your bug report.

@nick111
Thank you for the valuable information. I'll apply your solution to the code.
